version: "3.9"

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: respond_dashboard
    ports:
        - "8000:8000"
    env_file:
      - .env.example
    volumes:
      - ..:/app
    restart: unless-stopped